eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081
  
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user

      
          

